---
language: node_js
node_js:
  - "6"

sudo: required
addons:
  chrome: stable

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-default
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

install:
  - yarn install --no-lockfile

script:
  - ember try:each --skip-cleanup
